# Generated by Django 4.0.3 on 2022-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_stripe_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='note',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
