# Generated by Django 4.0.3 on 2022-05-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_pendingorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='pending_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.pendingorders'),
        ),
    ]
