# Generated by Django 4.0.3 on 2022-05-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderline_pending_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='pending_orders',
        ),
        migrations.AddField(
            model_name='orderline',
            name='pending_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.pendingorders'),
        ),
        migrations.AddField(
            model_name='pendingorders',
            name='order_line',
            field=models.ManyToManyField(related_name='lineitems', to='checkout.orderline'),
        ),
    ]
