# Generated by Django 4.0.3 on 2022-05-26 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_orderline_pending_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='pending_order',
        ),
        migrations.RemoveField(
            model_name='pendingorders',
            name='order_line',
        ),
        migrations.AddField(
            model_name='order',
            name='prep_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)]),
        ),
        migrations.AddField(
            model_name='pendingorders',
            name='estim_prep_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)]),
        ),
    ]
