# Generated by Django 4.0.3 on 2022-06-03 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_prep_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_intent', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('amount_captured', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('amount_refunded', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('card_brand', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cvc_check', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('card_country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('card_exp_month', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)])),
                ('card_exp_year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3333)])),
                ('card_last4', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order')),
            ],
        ),
    ]
