# Generated by Django 4.0.3 on 2022-04-07 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('', 'Choose Time'), ('1400', '14:00'), ('1430', '14:30'), ('1500', '15:00'), ('1530', '15:30'), ('1600', '16:30'), ('1630', '16:30'), ('1700', '17:00'), ('1730', '17:30'), ('1800', '18:00'), ('1830', '18:30'), ('1900', '19:00'), ('1930', '19:30'), ('2000', '20:00'), ('2030', '20:30'), ('2100', '21:00'), ('2130', '21:30'), ('2200', '22:00'), ('2230', '22:30')], max_length=10),
        ),
    ]
