# Generated by Django 4.0.3 on 2022-04-10 14:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('out_of_stock', models.BooleanField()),
                ('unit', models.CharField(choices=[('cl', 'cl'), ('unit', 'unit'), ('ml', 'ml'), ('L', 'L'), ('gr', 'gr'), ('mg', 'mg'), ('Kg', 'Kg')], default='cl', max_length=10)),
                ('price_per_unit', models.FloatField()),
                ('allowed_for_creation', models.BooleanField()),
                ('is_alcoholic', models.BooleanField()),
                ('alcohol_volume', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('gin', 'Gin'), ('rhum', 'Rhum'), ('vodka', 'Vodka'), ('soft', 'Soft drink'), ('garnish', 'Garnish'), ('special', 'Special'), ('whiskey', 'Whiskey'), ('liquor', 'Liquor'), ('triple sec', 'Triple sec')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ManyToManyField(to='menu.ingredient')),
                ('to_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='to_recipe',
            field=models.ManyToManyField(to='menu.recipe'),
        ),
    ]
