# Generated by Django 4.0.3 on 2022-04-14 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0005_alter_recipe_unique_together_remove_recipe_cocktail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('slug', models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('has_alcohol', models.BooleanField(default=False)),
                ('prep_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ordered', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('out_of_stock', models.BooleanField(blank=True, default=False)),
                ('unit', models.CharField(choices=[('cl', 'cl'), ('unit', 'unit'), ('ml', 'ml'), ('L', 'L'), ('gr', 'gr'), ('mg', 'mg'), ('Kg', 'Kg')], default='cl', max_length=10)),
                ('price_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('allowed_for_creation', models.BooleanField(blank=True, default=False)),
                ('has_alcohol', models.BooleanField(blank=True, default=False)),
                ('alcohol_volume', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('category', models.CharField(choices=[('gin', 'Gin'), ('rum', 'Rum'), ('vodka', 'Vodka'), ('soft', 'Soft drink'), ('garnish', 'Garnish'), ('tequila', 'Tequila'), ('whiskey', 'Whiskey'), ('liqueur', 'Liqueur'), ('brandy', 'Brandy'), ('wine', 'Wine'), ('beer', 'Beer')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'cocktail')},
            },
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='menu.Recipe', to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.subcategory'),
        ),
    ]
