# Generated by Django 4.0.3 on 2022-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('cl', 'cl'), ('unit', 'unit')], default='cl', max_length=10),
        ),
    ]
