# Generated by Django 4.0.3 on 2022-04-15 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
