# Generated by Django 4.0.3 on 2022-04-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_cocktail_is_double_alter_cocktail_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='is_double',
            new_name='has_size',
        ),
    ]
