# Generated by Django 4.0.3 on 2022-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_sub_category_category_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, null=True, to='menu.subcategory'),
        ),
    ]
