# Generated by Django 4.0.3 on 2022-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_cocktail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailsSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(blank=True, choices=[('sm', 'small'), ('md', 'medium'), ('lg', 'large'), ('simple', 'simple'), ('double', 'double'), ('triple', 'triple')], max_length=10, null=True)),
            ],
        ),
    ]
