# Generated by Django 4.0.3 on 2022-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_cocktailssize'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='menu.cocktailssize'),
        ),
    ]
