# Generated by Django 4.0.3 on 2022-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_cocktail_net_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailssize',
            name='sizes',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('single', 'single'), ('double', 'double'), ('triple', 'triple')], max_length=10, null=True),
        ),
    ]
