# Generated by Django 4.0.3 on 2022-04-26 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_cocktailssize_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
