# Generated by Django 4.0.3 on 2022-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_alter_cocktail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailssize',
            name='sizes',
            field=models.CharField(blank=True, choices=[('small', '125ml'), ('medium', '175ml'), ('large', '250ml'), ('single', 'single'), ('double', 'double'), ('triple', 'triple')], max_length=10, null=True),
        ),
    ]
