# Generated by Django 4.0.3 on 2022-05-26 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_alter_cocktailssize_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='prep_time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
