# Generated by Django 4.0.3 on 2022-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('menu', '0028_alter_cocktail_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='matching_questions',
            field=models.ManyToManyField(blank=True, null=True, to='match.matchingquestions'),
        ),
    ]
