# Generated by Django 4.0.3 on 2022-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_cocktail_matching_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='allow_match',
            field=models.BooleanField(default=False),
        ),
    ]
