# Generated by Django 4.0.3 on 2022-06-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_cocktail_allow_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cocktail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
