# Generated by Django 4.0.3 on 2022-06-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_remove_cocktail_net_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='has_alcohol',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='slug',
        ),
    ]
