# Generated by Django 4.0.3 on 2022-06-09 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_remove_cocktail_has_alcohol_remove_cocktail_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='net_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
