# Generated by Django 4.0.3 on 2022-06-09 12:08

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_cocktail_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='has_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
