# Generated by Django 4.0.3 on 2022-06-10 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_cocktail_has_alcohol_cocktail_rating_cocktail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
