# Generated by Django 4.0.3 on 2022-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_remove_cocktail_has_alcohol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_mixer',
            field=models.BooleanField(default=False),
        ),
    ]
