# Generated by Django 4.0.3 on 2022-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingquestions',
            name='value_answer',
        ),
        migrations.AlterField(
            model_name='matchingquestions',
            name='answer',
            field=models.CharField(choices=[('dry', '1'), ('sweet', '2'), ('party hard', '3'), ('party calm', '4'), ('romantic date', '5'), ('after work', '6'), ('party', '7'), ('single', '8'), ('double', '9'), ('vodka', '10'), ('rum', '11'), ('tequilla', '12'), ('old school', '13'), ('contempory', '14')], max_length=255, null=True),
        ),
    ]
