# Generated by Django 4.0.3 on 2022-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_remove_matchingquestions_value_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingquestions',
            name='answer',
            field=models.CharField(choices=[('1', 'dry'), ('2', 'sweet'), ('3', 'party hard'), ('4', 'party calm'), ('5', 'romantic date'), ('6', 'after work'), ('7', 'party'), ('8', 'single'), ('9', 'double'), ('10', 'vodka'), ('11', 'rum'), ('12', 'tequilla'), ('13', 'old school'), ('14', 'contempory')], max_length=255, null=True),
        ),
    ]
