# Generated by Django 4.0.3 on 2022-05-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_matchingquestions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingquestions',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
