# Generated by Django 4.0.3 on 2022-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_matchingquestions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyCheckMalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoy', models.BooleanField()),
            ],
        ),
    ]
