# Generated by Django 4.0.3 on 2022-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_enjoycheckmalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='enjoycheckmalt',
            name='non_enjoy',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enjoycheckmalt',
            name='enjoy',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
